---
- name: Install Lighthouse + Nginx
  hosts: lighthouse
  pre_tasks:
    - name: install epel + nginx
      block:
        - name: install epel
          ansible.builtin.yum:
            name:
              - epel-release
            state: present
        - name: install nginx
          ansible.builtin.yum:
            name:
              - nginx
            state: present
        - name: create cokfig nginx
          template:
            src: templates/nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            mode: 0644
        - name: install git
          ansible.builtin.yum:
            name: git
            state: present
      become: true
      notify: start_nginx
      tags: lighthouse
  tasks:
    - name: Copy lighthouse
      become: true
      git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir }}"
      tags: lighthouse
    - name: Create lighthouse config
      become: true
      template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify: reload_nginx
      tags: lighthouse
